name: Development

on:
  push:
    branches:
      - v0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pm2
        run: npm install pm2 -g
      - name: Install dependencies
        run : npm install
      - name: Build Next.js project
        run: npm run build
      - name: Stop previous Next.js process
        run: npx pm2 stop 0 || echo 'No previous process found'
      - name: Start Next.js project
        run: npm run start -- -p 3000

