name: Development

on:
  push:
    branches:
      - v0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo -u callnow bash -c '
            cd ~/actions-runner/_work/CallNowCMSWeb/CallNowCMSWeb/
            docker-compose down
            docker rm callnow-container || true
            docker rmi callnow-web || true
            docker build -t callnow-web .
            docker run -d --name callnow-container -p 3000:3000 callnow-web
            docker-compose up -d
            '
