name: Development

on:
  push:
    branches:
      - v0.1
  pull_request:
    branches:
      - v0.1

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Wait for app data
        run: sleep 5 && echo "Waiting to get app data"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

  deploy:
    needs: [build, checkout]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo -u callnow bash -c '
            cd ~/actions-runner/_work/CallNowCMSWeb/CallNowCMSWeb/
            rm -rf node_modules/
            npm cache clean --force
            npm install
            npm run build
            kill $(lsof -t -i:3000) || true
            nohup npm run start > /dev/null 2>&1 &
            '


