name: Development Workflow

on:
  push:
    branches:
      - v0.1

jobs:
  deploy:
    name: Deploy to DigitalOcean Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: 167.172.177.11
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .next
          target: /var/www/html

