name: CI/CD

on:
  push:
    branches:
      - v0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest' 

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install PM2
        run: npm install pm2 -g

      - name: Deploy app
        run: |
          pm2 delete my-app || true
          pm2 start npm --name "my-app" -- start
